#!/bin/bash
cmake -S llvm -B build -G "Ninja" -DLLVM_ENABLE_PROJECTS="clang" -DCMAKE_BUILD_TYPE=Debug -DLLVM_USE_LINKER=lld -DLLVM_PARALLEL_LINK_JOBS=1 -DLLVM_OPTIMIZED_TABLEGEN=true -DLLVM_TARGETS_TO_BUILD=host -DBUILD_SHARED_LIBS=true -DLLVM_USE_SPLIT_DWARF=true

